# Generated by Django 4.2.27 on 2026-01-15 10:43

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models

import apps.payouts.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR"), ("GBP", "GBP"), ("RUB", "RUB")],
                        default=apps.payouts.constants.Currency["USD"],
                        max_length=3,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=255, validators=[django.core.validators.MinLengthValidator(2)]
                    ),
                ),
                (
                    "recipient_account",
                    models.CharField(
                        max_length=34, validators=[django.core.validators.MinLengthValidator(8)]
                    ),
                ),
                ("recipient_bank_code", models.CharField(blank=True, default="", max_length=11)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default=apps.payouts.constants.PayoutStatus["PENDING"],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="", max_length=1000)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "payouts",
                "ordering": ["-created_at"],
            },
        ),
    ]
